name: Set Up JDK
description: Set up JDK with specific version
inputs:
  jdk-version:
    required: true
    description: The JDK version to use for the test
    default: '8'
runs:
  using: 'composite'
  steps:
    - name: 'Cache gradle dependencies'
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: 'Set up JDK ${{ inputs.jdk-version }}'
      uses: actions/setup-java@v2
      with:
        java-version: ${{ inputs.jdk-version }}
        distribution: 'zulu'
