name: Another Workflow

on:
  push:
    branches:
      - '*'
  pull_request:
    types: [ opened, synchronize, reopened ]

env:
  OSSRH_USERNAME: 'OSSRH_USERNAME'
  OSSRH_PASSWORD: 'OSSRH_PASSWORD'

jobs:
  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: 'Cancel previous runs'
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - name: 'Checkout repository'
        uses: actions/checkout@v2
      - uses: ./.github/actions/set-up-jdk
      - name: 'Run test'
        run: ./gradlew clean test
