name: CI

on:
  push:
    branches:
      - 'master'
      - 'release/*'
      - 'feature/*'
  pull_request:
    types: [ assigned ]

env:
  OSSRH_USERNAME: 'OSSRH_USERNAME'
  OSSRH_PASSWORD: 'OSSRH_PASSWORD'

jobs:
  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    timeout-minutes: 3
    strategy:
      matrix:
        java: [ '8', '11', '17', '18' ]
    steps:
      - name: 'Cancel previous runs'
        uses: styfle/cancel-workflow-action@0.10.1
        with:
          access_token: ${{ github.token }}
      - name: 'Checkout repository'
        uses: actions/checkout@v3
      - uses: ./.github/actions/set-up-jdk
        with:
          jdk-version: '${{ matrix.java }}'
      - name: 'Run test'
        run: ./gradlew clean test

  sonarqube:
    name: Sonarqube Report
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/set-up-jdk
        with:
          jdk-version: '11'
      - uses: ./.github/actions/sonarqube
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
